# Generated by Django 2.2.28 on 2025-05-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iduser', models.IntegerField(default=0)),
                ('content', models.TextField(max_length=1000)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
