# Generated by Django 2.2.28 on 2025-05-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='whoSend',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
