services:
  - type: web
    name: medicalcirta
    env: python
    buildCommand: |
      echo "python-3.8" > .python-version
      pip install -r requirements.txt
    startCommand: gunicorn medicalcirta.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.8
buildCommand: |
  pip install -r requirements.txt
  python manage.py collectstatic --noinput
  python manage.py migrate  # Optional
