# Generated by Django 2.2.28 on 2025-05-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iduser', models.IntegerField(default=0)),
                ('type_operation', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('detail', models.TextField(max_length=1000)),
            ],
        ),
    ]
