# Generated by Django 3.1.12 on 2025-06-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_videocallrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoCallRequest',
        ),
    ]
