# Generated by Django 2.2.28 on 2025-05-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=20)),
                ('email', models.TextField(max_length=30)),
                ('password', models.TextField(max_length=15)),
            ],
        ),
    ]
