# Generated by Django 3.1.12 on 2025-05-27 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_videocallrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoCallRequest',
        ),
    ]
