# Generated by Django 2.2.28 on 2025-05-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='detail',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='patient',
            name='disease',
            field=models.TextField(default='', max_length=500),
        ),
    ]
