# Generated by Django 3.1.12 on 2025-05-27 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20250527_2331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallRequest',
        ),
    ]
