# Generated by Django 2.2.28 on 2025-05-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iduser', models.IntegerField(default=0)),
                ('regime', models.TextField(max_length=100)),
                ('coloscopie', models.CharField(max_length=100)),
                ('sang', models.CharField(max_length=100)),
                ('echo', models.CharField(max_length=100)),
                ('poussee', models.CharField(max_length=100)),
                ('symp', models.CharField(max_length=100)),
            ],
        ),
    ]
